spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          time_zone: UTC
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driverClassName: org.h2.Driver
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: jdbc:h2:file:/home/${PC_USERNAME}/Code/WebTech/database
  h2:
    console:
      path: /db-console
      enabled: 'true'
  sql:
    init:
      mode: always
      platform: h2